### ISSUE TITLE
Unable to install *.*.7 versions with composer

### ISSUE THREAD

**Issue by bplaquevent** [mollie/orocommerce#15]
Hi,

It is currently not possible to install the \*.\*.7 versions of the module with composer (tried with composer v1 and v2):

```
$ composer show -a mollie/orocommerce -vv                                                                                                                                                                                                  Reading composer.json of mollie/orocommerce (4.2.7)
Skipped tag 4.2.7, tag (4.2.7.0) does not match version (4.1.5.0) in composer.json
Reading composer.json of mollie/orocommerce (4.1.7)
Skipped tag 4.1.7, tag (4.1.7.0) does not match version (4.1.5.0) in composer.json
Reading composer.json of mollie/orocommerce (4.0.7)
Skipped tag 4.0.7, tag (4.0.7.0) does not match version (4.0.5.0) in composer.json
Reading composer.json of mollie/orocommerce (3.1.7)
Skipped tag 3.1.7, tag (3.1.7.0) does not match version (3.1.4.0) in composer.json
```

It seems it's due to the remaining "version" property in the composer.json on these tags not matching the tag.

Are these tags production ready ?

Regards,

Ben.

**Comment by logeecom** [comment]
The version in the Composer file doesn’t match the actual release version in any of the currently released versions. Our team is working on a new release that will fix this issue.

**Comment by alexisLeroux1** [comment]
> The version in the Composer file doesn’t match the actual release version in any of the currently released versions. Our team is working on a new release that will fix this issue.

Hello, do you know when the new release will be available ?

**Comment by logeecom** [comment]
> > The version in the Composer file doesn’t match the actual release version in any of the currently released versions. Our team is working on a new release that will fix this issue.
> 
> Hello, do you know when the new release will be available ?

We expect the new release during next week.

**Comment by logeecom** [comment]
New module versions x.x.8 with fixed Composer version tags have been released.
