### ISSUE TITLE
Compatibility for OroCommerce 6.0.x applications

### ISSUE THREAD

**Issue by gregdevuyst** [mollie/orocommerce#44]
Hello,

I've contacted your support service about this as well: `Ticket ID 2071497`

It seems that you are working on making the package compatible for OroCommerce 6.0.x environments (I've seen some branches), do you guys have any idea when it will be officially released through composer?

Kind regards,
Gregori De Vuyst

**Comment by logeecom** [comment]
Hello @gregdevuyst,

Please note that our team already released a new version of our module that supports both OroCommerce 5 and 6.

You can find the mentioned version here: https://github.com/mollie/orocommerce/releases/tag/6.0.0 

Thank you,

Kind regards.
